-- Tabela de histórico das migrations do EF Core
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE "__EFMigrationsHistory" (
        "MigrationId" NVARCHAR2(150) NOT NULL,
        "ProductVersion" NVARCHAR2(32) NOT NULL,
        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- -955 = table already exists
            RAISE;
        END IF;
END;


-- Tabela Clientes
CREATE TABLE Clientes (
    Id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    NomeCompleto NVARCHAR2(2000) NOT NULL,
    Cpf NVARCHAR2(2000) NOT NULL,
    Email NVARCHAR2(2000) NOT NULL,
    CONSTRAINT PK_Clientes PRIMARY KEY (Id)
);


-- Tabela ContasBancarias
CREATE TABLE ContasBancarias (
    Id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    NumeroConta NVARCHAR2(2000) NOT NULL,
    Agencia NVARCHAR2(2000) NOT NULL,
    TipoConta NVARCHAR2(2000) NOT NULL,
    ClienteId NUMBER(10) NOT NULL,
    CONSTRAINT PK_ContasBancarias PRIMARY KEY (Id),
    CONSTRAINT FK_ContasBancarias_Clientes_ClienteId FOREIGN KEY (ClienteId) REFERENCES Clientes (Id) ON DELETE CASCADE
);


-- Tabela Transacoes
CREATE TABLE Transacoes (
    Id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    Tipo NVARCHAR2(2000) NOT NULL,
    Valor DECIMAL(18, 2) NOT NULL,
    Data TIMESTAMP(7) NOT NULL,
    ContaBancariaId NUMBER(10) NOT NULL,
    CONSTRAINT PK_Transacoes PRIMARY KEY (Id),
    CONSTRAINT FK_Transacoes_ContasBancarias_ContaBancariaId FOREIGN KEY (ContaBancariaId) REFERENCES ContasBancarias (Id) ON DELETE CASCADE
);


-- Índices
CREATE INDEX IX_ContasBancarias_ClienteId ON ContasBancarias (ClienteId);

CREATE INDEX IX_Transacoes_ContaBancariaId ON Transacoes (ContaBancariaId);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251006232626_InitialCreate', '9.0.9');
